version: '3.7'
services:
  db:
    container_name: 'magalu-db'
    build: './db'
    restart: always
    volumes:
      - 'postgres_data:/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      DATABASE_DB: magalu_db
    networks:
      - back-tier
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

volumes:
  postgres_data: {}

networks:
  back-tier:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '172.50.0.0/28'
